# Generated by Django 4.1.1 on 2022-09-12 19:18

from django.db import models, migrations

def transfer(apps, schema_editor):
    Student = apps.get_model('school', 'Student')

    for student in Student.objects.all():
        student.teachers.add(student.teacher)

class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_add_manytomanyfield'),
    ]

    operations = [migrations.RunPython(transfer)
    ]
